# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [1]:
#code here
import numpy as np
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
array_2d = array_1d.reshape(3, 4)
Array_1d = np.array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])
Array_2d = Array_1d.reshape(3, 4)
concatenated_horizontal = np.concatenate((array_2d, Array_2d), axis=1)
concatenated_vertical = np.concatenate((array_2d, Array_2d), axis=0)

print("Reshaped 2D array 1:")
print(array_2d)
print("\nReshaped 2D array 2:")
print(Array_2d)
print("\nConcatenated horizontally:")
print(concatenated_horizontal)
print("\nConcatenated vertically:")
print(concatenated_vertical)

Reshaped 2D array 1:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped 2D array 2:
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

Concatenated horizontally:
[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]

Concatenated vertically:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [2]:
#code here
def classify_emails(emails):
    important_keywords = ["urgent", "important", "action required", "deadline", 'note','action']
    promotions_keywords = ["sale", "discount", "deal", "offer", "save upto"]
    spam_keywords = ["lottery", "sale your AC", "free", "claim your prize" , "prize"]

    important_emails = []
    promotions_emails = []
    spam_emails = []

    for email in emails:
        lower_case_email = email.lower()
#appending lists of respective emails
        if any(keyword in lower_case_email for keyword in important_keywords):
            important_emails.append(email)
        elif any(keyword in lower_case_email for keyword in promotions_keywords):
            promotions_emails.append(email)
        elif any(keyword in lower_case_email for keyword in spam_keywords):
            spam_emails.append(email)

    return important_emails, promotions_emails, spam_emails


Example_Emails = [
    "Hey, urgent meeting at 3 PM today!",
    "Special offer! Get 20% off on your next purchase!",
    "Verify your account to secure your data.",
    "Important notice: Action required for project deadline.",
    "Limited-time sale! Grab your favorite items now.",
    "Win a free vacation! Click here for details.",
    "Critical: Immediate action needed for system update.",
    "Now save upto 70% dicount on daraz",
    "sale your AC at a reasonable price" 
]

important, promotions, spam = classify_emails(Example_Emails)

print("Important Emails: ",important)

print("\nPromotions Emails: ",promotions)


print("\nSpam Emails: ",spam)

Important Emails:  ['Hey, urgent meeting at 3 PM today!', 'Important notice: Action required for project deadline.', 'Critical: Immediate action needed for system update.']

Promotions Emails:  ['Special offer! Get 20% off on your next purchase!', 'Limited-time sale! Grab your favorite items now.', 'Now save upto 70% dicount on daraz', 'sale your AC at a reasonable price']

Spam Emails:  ['Win a free vacation! Click here for details.']


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [4]:
#code here
Mydictionary = {
    'sir':'Señor',
    'give': 'Dar',
    'me': 'python',
    'a+ grade':'Grado A+',
    'please': 'por favor',
    "hello": "hola",
    "goodbye": "adiós",
    "thank you": "gracias",
}
while True:
    user_input = input("Enter an English word (or type 'exit' to quit): ").lower()

    if user_input == 'exit':
        print("OK Thankyou")
        break

    translation = Mydictionary.get(user_input, "Translation not available")
    print(f"Spanish translation: {translation}\n")


Enter an English word (or type 'exit' to quit):  sir


Spanish translation: Señor



Enter an English word (or type 'exit' to quit):  hello


Spanish translation: hola



Enter an English word (or type 'exit' to quit):  a+


Spanish translation: Translation not available



Enter an English word (or type 'exit' to quit):  exit


OK Thankyou


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

Some tree example

In [5]:
import pandas as pd
data=pd.read_csv('https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv',sep=',',index_col='Rank')
data

Name Platform    Year  \
Rank                                                                       
1                                            Wii Sports      Wii  2006.0   
2                                     Super Mario Bros.      NES  1985.0   
3                                        Mario Kart Wii      Wii  2008.0   
4                                     Wii Sports Resort      Wii  2009.0   
5                              Pokemon Red/Pokemon Blue       GB  1996.0   
...                                                 ...      ...     ...   
16596                Woody Woodpecker in Crazy Castle 5      GBA  2002.0   
16597                     Men in Black II: Alien Escape       GC  2003.0   
16598  SCORE International Baja 1000: The Official Game      PS2  2008.0   
16599                                        Know How 2       DS  2010.0   
16600                                  Spirits & Spells      GBA  2003.0   

              Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  \
Rank                                                                         
1            Sports    Nintendo     41.49     29.02      3.77         8.46   
2          Platform    Nintendo     29.08      3.58      6.81         0.77   
3            Racing    Nintendo     15.85     12.88      3.79         3.31   
4            Sports    Nintendo     15.75     11.01      3.28         2.96   
5      Role-Playing    Nintendo     11.27      8.89     10.22         1.00   
...             ...         ...       ...       ...       ...          ...   
16596      Platform       Kemco      0.01      0.00      0.00         0.00   
16597       Shooter  Infogrames      0.01      0.00      0.00         0.00   
16598        Racing  Activision      0.00      0.00      0.00         0.00   
16599        Puzzle    7G//AMES      0.00      0.01      0.00         0.00   
16600      Platform     Wanadoo      0.01      0.00      0.00         0.00   

       Global_Sales  
Rank                 
1             82.74  
2             40.24  
3             35.82  
4             33.00  
5             31.37  
...             ...  
16596          0.01  
16597          0.01  
16598          0.01  
16599          0.01  
16600          0.01  

[16598 rows x 10 columns]

In [6]:
print("The total global sales are: ",data['Global_Sales'].sum())

The total global sales are:  8920.44


In [7]:
maximum =data.loc[data['Global_Sales'].idxmax()]
print("Game with highest global sale: ",maximum['Name'])
print("Highest sale: ",data['Global_Sales'].max())

Game with highest global sale:  Wii Sports
Highest sale:  82.74


In [8]:
print("Average sales for NA_Sales is: ",data['NA_Sales'].mean())
print("Average sales for EU_Sales is: ",data['EU_Sales'].mean())
print("Average sales for JP_Sales is: ",data['JP_Sales'].mean())
print("Average sales for Other_Sales is: ",data['Other_Sales'].mean())

Average sales for NA_Sales is:  0.26466742981082064
Average sales for EU_Sales is:  0.14665200626581515
Average sales for JP_Sales is:  0.077781660441017
Average sales for Other_Sales is:  0.0480630196409206


In [9]:
All_GlobalSales_Genres = data.groupby('Genre')['Global_Sales'].sum()
Top_Five = All_GlobalSales_Genres.nlargest(5)
print("top 5 most popular game genres based on global sales:",Top_Five)

top 5 most popular game genres based on global sales: Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64


In [10]:
print("Average sales for NA_Sales is: ",data['NA_Sales'].mean())
print("Average sales for EU_Sales is: ",data['EU_Sales'].mean())
print("Average sales for JP_Sales is: ",data['JP_Sales'].mean())
print("Average sales for Other_Sales is: ",data['Other_Sales'].mean())
#now calculating for top genre in NA_Sales
getting_NA_Genres = data.groupby('Genre')['NA_Sales'].sum()
top = getting_NA_Genres.nlargest(1)
print("Most popular genre in North America (NA_Sales): ",top)

Average sales for NA_Sales is:  0.26466742981082064
Average sales for EU_Sales is:  0.14665200626581515
Average sales for JP_Sales is:  0.077781660441017
Average sales for Other_Sales is:  0.0480630196409206
Most popular genre in North America (NA_Sales):  Genre
Action    877.83
Name: NA_Sales, dtype: float64


In [11]:
data.tail(10)

Name Platform    Year  \
Rank                                                                        
16591                                   Mega Brain Boost       DS  2008.0   
16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV  2016.0   
16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP  2007.0   
16594                                Myst IV: Revelation       PC  2004.0   
16595                                           Plushees       DS  2008.0   
16596                 Woody Woodpecker in Crazy Castle 5      GBA  2002.0   
16597                      Men in Black II: Alien Escape       GC  2003.0   
16598   SCORE International Baja 1000: The Official Game      PS2  2008.0   
16599                                         Know How 2       DS  2010.0   
16600                                   Spirits & Spells      GBA  2003.0   

              Genre              Publisher  NA_Sales  EU_Sales  JP_Sales  \
Rank                                                                       
16591        Puzzle  Majesco Entertainment      0.01      0.00      0.00   
16592        Action        dramatic create      0.00      0.00      0.01   
16593  Role-Playing     Falcom Corporation      0.00      0.00      0.01   
16594     Adventure                Ubisoft      0.01      0.00      0.00   
16595    Simulation              Destineer      0.01      0.00      0.00   
16596      Platform                  Kemco      0.01      0.00      0.00   
16597       Shooter             Infogrames      0.01      0.00      0.00   
16598        Racing             Activision      0.00      0.00      0.00   
16599        Puzzle               7G//AMES      0.00      0.01      0.00   
16600      Platform                Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
Rank                              
16591          0.0          0.01  
16592          0.0          0.01  
16593          0.0          0.01  
16594          0.0          0.01  
16595          0.0          0.01  
16596          0.0          0.01  
16597          0.0          0.01  
16598          0.0          0.01  
16599          0.0          0.01  
16600          0.0          0.01

In [12]:
All_platforms = data.groupby('Platform')['Global_Sales'].sum()
Top_three = All_platforms.nlargest(3)
print("Top 3 gaming platforms with the highest global sales.: ",Top_three)

Top 3 gaming platforms with the highest global sales.:  Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


In [13]:
total_of_All_GlobalSales = data['Global_Sales'].sum()
genre = data.groupby('Genre')['Global_Sales'].sum()
share = (genre / total_of_All_GlobalSales)*100
print("Market share (percentage of global sales) for each genre: ")
print(share)

Market share (percentage of global sales) for each genre: 
Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64


In [3]:
# import pandas as pd

# # Create a DataFrame to represent a tree
# data = {
#     'node': ['A', 'B', 'C', 'D', 'E', 'F'],
#     'parent': [None, 'A', 'A', 'B', 'B', 'C']
# }
# df = pd.DataFrame(data)

# print(df)


In [2]:
# pip install networkx


In [1]:
# import pandas as pd
# import networkx as nx
# import matplotlib.pyplot as plt

# # Create a DataFrame representing edges in a graph
# data = {
#     'from': ['A', 'A', 'B', 'C', 'D'],
#     'to': ['B', 'C', 'D', 'E', 'E']
# }
# edges = pd.DataFrame(data)

# # Create a graph from the edges DataFrame
# G = nx.from_pandas_edgelist(edges, 'from', 'to')

# # Draw the graph
# nx.draw(G, with_labels=True)
# plt.show()

# # Analyze the graph
# print("Nodes:", G.nodes())
# print("Edges:", G.edges())
# print("Degree for each Node:", dict(G.degree()))
